# path to sample sheet (TSV format, columns: sample_name, fq1, fq2)
samples: ./config/samples.tsv

# Tools paths
fastqc: /mnt/storage/spack/share/spack/modules/linux-ubuntu16.04-x86_64/fastqc-0.11.7-gcc-5.4.0-hjgfsw2
star: /mnt/storage/apps/STAR/2.7.10a
rsem: /mnt/storage/spack/share/spack/modules/linux-ubuntu16.04-x86_64/rsem-1.3.1-gcc-5.4.0-ml3p6ok
salmon: /mnt/storage/apps/salmon-1.10.1
snakemake: /mnt/storage/apps/Mambaforge-23.1.0-1/envs/snakemake

# reference files paths
annotation_path: /mnt/storage/labs/sviswanathan/snakemake_RNAseq_2024/Human_genome_2024/annotation_ensblID_genesymbol_transcriptID_20240512.txt
STAR_index_path: /mnt/storage/labs/sviswanathan/snakemake_RNAseq_2024/Human_genome_2024/STAR_index
gtf_path: /mnt/storage/labs/sviswanathan/snakemake_RNAseq_2024/Human_genome_2024/gencode.v45.primary_assembly.annotation.gtf
salmon_index_path: /mnt/storage/labs/sviswanathan/snakemake_RNAseq_2024/Human_genome_2024/salmon_index/GRCh38.transcripts_index
fa_path: /mnt/storage/labs/sviswanathan/snakemake_RNAseq_2024/Human_genome_2024/GRCh38.primary_assembly.genome.fa
